---
# Authentication Configuration Tasks

- name: Prompt for AUTH_PROVIDER
  ansible.builtin.pause:
    prompt: |
      AUTH_PROVIDER (Valid options are 'ad' or 'keycloak'):
  register: dibbs_ecr_viewer_auth_provider_input

- name: Set AUTH_PROVIDER fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_auth_provider: "{{ dibbs_ecr_viewer_auth_provider_input.user_input }}"

- name: Add AUTH_PROVIDER to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'AUTH_PROVIDER="{{ dibbs_ecr_viewer_auth_provider }}"'
    create: true
    mode: '0644'

- name: Prompt for AUTH_CLIENT_ID
  ansible.builtin.pause:
    prompt: |
      AUTH_CLIENT_ID:
  register: dibbs_ecr_viewer_auth_client_id_input

- name: Set AUTH_CLIENT_ID fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_auth_client_id: "{{ dibbs_ecr_viewer_auth_client_id_input.user_input }}"

- name: Add AUTH_CLIENT_ID to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'AUTH_CLIENT_ID="{{ dibbs_ecr_viewer_auth_client_id }}"'
    create: true
    mode: '0644'

- name: Prompt for AUTH_CLIENT_SECRET
  ansible.builtin.pause:
    prompt: |
      AUTH_CLIENT_SECRET:
  register: dibbs_ecr_viewer_auth_client_secret_input

- name: Set AUTH_CLIENT_SECRET fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_auth_client_secret: "{{ dibbs_ecr_viewer_auth_client_secret_input.user_input }}"

- name: Add AUTH_CLIENT_SECRET to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'AUTH_CLIENT_SECRET="{{ dibbs_ecr_viewer_auth_client_secret }}"'
    create: true
    mode: '0644'

- name: Prompt for AUTH_ISSUER
  ansible.builtin.pause:
    prompt: |
      AUTH_ISSUER:
  register: dibbs_ecr_viewer_auth_issuer_input

- name: Set AUTH_ISSUER fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_auth_issuer: "{{ dibbs_ecr_viewer_auth_issuer_input.user_input }}"

- name: Add AUTH_ISSUER to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'AUTH_ISSUER="{{ dibbs_ecr_viewer_auth_issuer }}"'
    create: true
    mode: '0644'

- name: Prompt for AUTH_SESSION_DURATION_MIN (optional)
  ansible.builtin.pause:
    prompt: |
      AUTH_SESSION_DURATION_MIN (Optional: leave blank for use defaults):
  register: dibbs_ecr_viewer_auth_session_duration_min_input

- name: Set AUTH_SESSION_DURATION_MIN fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_auth_session_duration_min: "{{ dibbs_ecr_viewer_auth_session_duration_min_input.user_input }}"

- name: Add AUTH_SESSION_DURATION_MIN to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'AUTH_SESSION_DURATION_MIN="{{ dibbs_ecr_viewer_auth_session_duration_min }}"'
    create: true
    mode: '0644'

- name: Prompt for NEXTAUTH_URL
  ansible.builtin.pause:
    prompt: |
      NEXTAUTH_URL (URL for the eCR Viewer application authentication: http(s)://(DOMAIN||IP:PORT)/ecr-viewer/api/auth/):
  register: dibbs_ecr_viewer_nextauth_url_input

- name: Set NEXTAUTH_URL fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_nextauth_url: "{{ dibbs_ecr_viewer_nextauth_url_input.user_input }}"

- name: Add NEXTAUTH_URL to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'NEXTAUTH_URL="{{ dibbs_ecr_viewer_nextauth_url }}"'
    create: true
    mode: '0644'
