---
# Azure Configuration Tasks

- name: Prompt for AZURE_STORAGE_CONNECTION_STRING
  ansible.builtin.pause:
    prompt: |
      AZURE_STORAGE_CONNECTION_STRING:
  register: dibbs_ecr_viewer_azure_storage_connection_string_input

- name: Set AZURE_STORAGE_CONNECTION_STRING fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_azure_storage_connection_string: "{{ dibbs_ecr_viewer_azure_storage_connection_string_input.user_input }}"

- name: Add AZURE_STORAGE_CONNECTION_STRING to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'AZURE_STORAGE_CONNECTION_STRING="{{ dibbs_ecr_viewer_azure_storage_connection_string }}"'
    create: true
    mode: '0644'

- name: Prompt for AZURE_CONTAINER_NAME
  ansible.builtin.pause:
    prompt: |
      AZURE_CONTAINER_NAME:
  register: dibbs_ecr_viewer_azure_container_name_input

- name: Set AZURE_CONTAINER_NAME fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_azure_container_name: "{{ dibbs_ecr_viewer_azure_container_name_input.user_input }}"

- name: Add AZURE_CONTAINER_NAME to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'AZURE_CONTAINER_NAME="{{ dibbs_ecr_viewer_azure_container_name }}"'
    create: true
    mode: '0644'
