---
# Create project directories

- name: Create project directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ dibbs_ecr_viewer_dir }}"
    state: directory
    mode: '0755'

- name: Create docker subdirectory
  ansible.builtin.file:
    path: "{{ dibbs_ecr_viewer_dir }}/docker"
    state: directory
    mode: '0755'

# Copy project files to target location
- name: Copy project files to target directory
  ansible.builtin.copy:
    src: "{{ dibbs_playbook_dir }}/project/"
    dest: "{{ dibbs_ecr_viewer_dir }}/"
    remote_src: true
