---
# NBS Configuration Tasks

- name: Prompt for NBS_API_PUB_KEY
  ansible.builtin.pause:
    prompt: |
      NBS_API_PUB_KEY:
  register: dibbs_ecr_viewer_nbs_api_pub_key_input

- name: Set NBS_API_PUB_KEY fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_nbs_api_pub_key: "{{ dibbs_ecr_viewer_nbs_api_pub_key_input.user_input }}"

- name: Add NBS_API_PUB_KEY to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_playbook_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'NBS_API_PUB_KEY="{{ dibbs_ecr_viewer_nbs_api_pub_key }}"'
    create: true
    mode: '0644'

- name: Prompt for NBS_PUB_KEY
  ansible.builtin.pause:
    prompt: |
      NBS_PUB_KEY:
  register: dibbs_ecr_viewer_nbs_pub_key_input

- name: Set NBS_PUB_KEY fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_nbs_pub_key: "{{ dibbs_ecr_viewer_nbs_pub_key_input.user_input }}"

- name: Add NBS_PUB_KEY to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_playbook_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'NBS_PUB_KEY="{{ dibbs_ecr_viewer_nbs_pub_key }}"'
    create: true
    mode: '0644'
