---
# NextAuth Configuration Tasks

- name: Prompt for NEXTAUTH_SECRET
  ansible.builtin.pause:
    prompt: |
      NEXTAUTH_SECRET (Generate a random secret using: openssl rand -base64 32):
  register: dibbs_ecr_viewer_nextauth_secret_input

- name: Set NEXTAUTH_SECRET fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_nextauth_secret: "{{ dibbs_ecr_viewer_nextauth_secret_input.user_input }}"

- name: Add NEXTAUTH_SECRET to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_wizard_file }}"
    line: 'NEXTAUTH_SECRET="{{ dibbs_ecr_viewer_nextauth_secret }}"'
    create: true
    mode: '0644'
