---
# Optional Configuration Tasks

- name: Prompt for SAVE_XML (optional)
  ansible.builtin.pause:
    prompt: |
      SAVE_XML (Optional: leave blank for use defaults):
  register: dibbs_ecr_viewer_save_xml_input

- name: Set SAVE_XML fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_save_xml: "{{ dibbs_ecr_viewer_save_xml_input.user_input }}"

- name: Add SAVE_XML to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_playbook_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'SAVE_XML="{{ dibbs_ecr_viewer_save_xml }}"'
    create: true
    mode: '0644'

- name: Prompt for DISPLAY_FEEDBACK_LINKS (optional)
  ansible.builtin.pause:
    prompt: |
      DISPLAY_FEEDBACK_LINKS (Optional: leave blank for use defaults):
  register: dibbs_ecr_viewer_display_feedback_links_input

- name: Set DISPLAY_FEEDBACK_LINKS fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_display_feedback_links: "{{ dibbs_ecr_viewer_display_feedback_links_input.user_input }}"

- name: Add DISPLAY_FEEDBACK_LINKS to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_playbook_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'DISPLAY_FEEDBACK_LINKS="{{ dibbs_ecr_viewer_display_feedback_links }}"'
    create: true
    mode: '0644'

- name: Prompt for ECR_PROCESSING_TIMEOUT (optional)
  ansible.builtin.pause:
    prompt: |
      ECR_PROCESSING_TIMEOUT (Optional: leave blank for use defaults):
  register: dibbs_ecr_viewer_ecr_processing_timeout_input

- name: Set ECR_PROCESSING_TIMEOUT fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_ecr_processing_timeout: "{{ dibbs_ecr_viewer_ecr_processing_timeout_input.user_input }}"

- name: Add ECR_PROCESSING_TIMEOUT to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_playbook_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'ECR_PROCESSING_TIMEOUT="{{ dibbs_ecr_viewer_ecr_processing_timeout }}"'
    create: true
    mode: '0644'
