---
# PostgreSQL Configuration Tasks

- name: Prompt for DATABASE_URL
  ansible.builtin.pause:
    prompt: |
      DATABASE_URL (PostgreSQL connection string format: postgres://USER:PASSWORD@HOST:PORT/DATABASE_NAME):
  register: database_url_input

- name: Set DATABASE_URL fact
  ansible.builtin.set_fact:
    DATABASE_URL: "{{ database_url_input.user_input }}"

- name: Add DATABASE_URL to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'DATABASE_URL="{{ DATABASE_URL }}"'
    create: true
    mode: '0644'

- name: Prompt for METADATA_DATABASE_SCHEMA
  ansible.builtin.pause:
    prompt: |
      METADATA_DATABASE_SCHEMA (Schema options are: 'core' or 'extended'):
  register: metadata_schema_input

- name: Set METADATA_DATABASE_SCHEMA fact
  ansible.builtin.set_fact:
    METADATA_DATABASE_SCHEMA: "{{ metadata_schema_input.user_input }}"

- name: Add METADATA_DATABASE_SCHEMA to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'METADATA_DATABASE_SCHEMA="{{ METADATA_DATABASE_SCHEMA }}"'
    create: true
    mode: '0644'

- name: Prompt for METADATA_DATABASE_MIGRATION_SECRET
  ansible.builtin.pause:
    prompt: |
      METADATA_DATABASE_MIGRATION_SECRET (Migration secret used to trigger migrations):
  register: migration_secret_input

- name: Set METADATA_DATABASE_MIGRATION_SECRET fact
  ansible.builtin.set_fact:
    METADATA_DATABASE_MIGRATION_SECRET: "{{ migration_secret_input.user_input }}"

- name: Add METADATA_DATABASE_MIGRATION_SECRET to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_dir }}/docker/dibbs-ecr-viewer.wizard"
    line: 'METADATA_DATABASE_MIGRATION_SECRET="{{ METADATA_DATABASE_MIGRATION_SECRET }}"'
    create: true
    mode: '0644'
