---
# Install Docker and required system packages

# Fedora
- name: Add signing key for Docker repository (Fedora)
  ansible.builtin.rpm_key:
    key: "https://download.docker.com/linux/{{ (ansible_distribution | lower) }}/gpg"
    state: present
  when: ansible_facts['distribution'] == "Fedora"

- name: Add Docker repository (Fedora)
  ansible.builtin.yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/{{ (ansible_distribution | lower) }}/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ (ansible_distribution | lower) }}/gpg"
  when: ansible_facts['distribution'] == "Fedora"

- name: Install Docker packages (Fedora)
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_facts['distribution'] == "Fedora"
  notify: Restart and enable docker

# Debian/Ubuntu
- name: Install required system packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker GPG apt Key for Ubuntu
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Add Docker Repository for Ubuntu
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Docker packages (Ubuntu)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"
  notify: Restart and enable docker

- name: Add Docker GPG apt Key for Debian
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_facts['distribution'] == "Debian"

- name: Add Docker Repository for Debian
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == "Debian"

- name: Install Docker packages (Debian)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
  when: ansible_facts['distribution'] == "Debian"
  notify: Restart and enable docker

# Generic - start Docker service
- name: Start Docker service
  ansible.builtin.systemd:
    name: "docker"
    enabled: true
    state: started
  notify: Restart and enable docker
