---
# SQL Server Configuration Tasks

- name: Prompt for SQL_SERVER_USER
  ansible.builtin.pause:
    prompt: |
      SQL_SERVER_USER:
  register: dibbs_ecr_viewer_sql_server_user_input

- name: Set SQL_SERVER_USER fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_sql_server_user: "{{ dibbs_ecr_viewer_sql_server_user_input.user_input }}"

- name: Add SQL_SERVER_USER to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_wizard_file }}"
    line: 'SQL_SERVER_USER="{{ dibbs_ecr_viewer_sql_server_user }}"'
    create: true
    mode: '0644'

- name: Prompt for SQL_SERVER_PASSWORD
  ansible.builtin.pause:
    prompt: |
      SQL_SERVER_PASSWORD:
  register: dibbs_ecr_viewer_sql_server_password_input

- name: Set SQL_SERVER_PASSWORD fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_sql_server_password: "{{ dibbs_ecr_viewer_sql_server_password_input.user_input }}"

- name: Add SQL_SERVER_PASSWORD to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_wizard_file }}"
    line: 'SQL_SERVER_PASSWORD="{{ dibbs_ecr_viewer_sql_server_password }}"'
    create: true
    mode: '0644'

- name: Prompt for SQL_SERVER_HOST
  ansible.builtin.pause:
    prompt: |
      SQL_SERVER_HOST:
  register: dibbs_ecr_viewer_sql_server_host_input

- name: Set SQL_SERVER_HOST fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_sql_server_host: "{{ dibbs_ecr_viewer_sql_server_host_input.user_input }}"

- name: Add SQL_SERVER_HOST to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_wizard_file }}"
    line: 'SQL_SERVER_HOST="{{ dibbs_ecr_viewer_sql_server_host }}"'
    create: true
    mode: '0644'

- name: Prompt for DB_CIPHER
  ansible.builtin.pause:
    prompt: |
      DB_CIPHER:
  register: dibbs_ecr_viewer_db_cipher_input

- name: Set DB_CIPHER fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_db_cipher: "{{ dibbs_ecr_viewer_db_cipher_input.user_input }}"

- name: Add DB_CIPHER to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_wizard_file }}"
    line: 'DB_CIPHER="{{ dibbs_ecr_viewer_db_cipher }}"'
    create: true
    mode: '0644'

- name: Prompt for METADATA_DATABASE_SCHEMA
  ansible.builtin.pause:
    prompt: |
      METADATA_DATABASE_SCHEMA (Schema options are: 'core' or 'extended'):
  register: dibbs_ecr_viewer_metadata_database_schema_input

- name: Set METADATA_DATABASE_SCHEMA fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_metadata_database_schema: "{{ dibbs_ecr_viewer_metadata_database_schema_input.user_input }}"

- name: Add METADATA_DATABASE_SCHEMA to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_wizard_file }}"
    line: 'METADATA_DATABASE_SCHEMA="{{ dibbs_ecr_viewer_metadata_database_schema }}"'
    create: true
    mode: '0644'

- name: Prompt for METADATA_DATABASE_MIGRATION_SECRET
  ansible.builtin.pause:
    prompt: |
      METADATA_DATABASE_MIGRATION_SECRET (Migration secret used to trigger
      migrations; one will be generated and output to ecr-viewer logs if you
      do not provide one):
  register: dibbs_ecr_viewer_metadata_database_migration_secret_input

- name: Set METADATA_DATABASE_MIGRATION_SECRET fact
  ansible.builtin.set_fact:
    dibbs_ecr_viewer_metadata_database_migration_secret: "{{ dibbs_ecr_viewer_metadata_database_migration_secret_input.user_input }}"

- name: Add METADATA_DATABASE_MIGRATION_SECRET to wizard file
  ansible.builtin.lineinfile:
    path: "{{ dibbs_ecr_viewer_wizard_file }}"
    line: 'METADATA_DATABASE_MIGRATION_SECRET="{{ dibbs_ecr_viewer_metadata_database_migration_secret }}"'
    create: true
    mode: '0644'
