---
# Handlers for dibbs_ecr_viewer role

- name: Reload fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: reloaded
    enabled: true

- name: Reload docker
  ansible.builtin.systemd:
    name: docker
    state: reloaded
    enabled: true
