---
# Default variables for dibbs_ecr_viewer role

dibbs_ecr_viewer_playbook_dir: "{{ lookup('env', 'DIBBS_PLAYBOOK_DIR') | default(lookup('env', 'HOME') + '/dibbs-ecr-viewer-playbook', true) }}"
ansible_python_interpreter: /usr/bin/python3

# Docker user configuration
dibbs_ecr_viewer_docker_user_name: ecr-viewer
